### ISSUE TITLE
chain file headers

### ISSUE THREAD

**Issue by kingralph80** [informationsea/transanno#1]
Hi,

Thank you for this tool. Its a really nice liftover tool which supports also lifting to a different species. We create chain files from GenomeAlignmentTools, and some tools, especially when starting from maf files leave a #comment header in the chain files:

e.g. 
##matrix=axtChain 16 91,-114,-31,-123,-114,100,-125,-31,-31,-125,100,-114,-123,-31,-114,91
##gapPenalties=axtChain O=400 E=30

these headers are commented by ## or #
However, for transanno 0.2.1 this causes an error. Could you add ignoring # or ## commented headers in chain files?

**Comment by informationsea** [comment]
Thank you for using. I fixed this issue and release as version 0.2.2 ( https://github.com/informationsea/transanno/releases/tag/v0.2.2 ).
