### ISSUE TITLE
Cannot find CIGER (minimap2chain)

### ISSUE THREAD

**Issue by makopyan** [informationsea/transanno#2]
Using the linux binary release 0.2.4, there is an error when using `minimap2chain`. 

```
> transanno minimap2chain aln.paf --output aln.chain 
thread 'main' panicked at 'Cannot find CIGER', transanno/src/commands/minimap2chain.rs:127:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by informationsea** [comment]
Which version of minimap2 did you use and what options did use to create `aln.paf`? transanno failed to find a column starts with `cg:Z:`.

**Comment by makopyan** [comment]
Thanks! I just had to re-run minimap2 with the -c option to get the CIGAR string in the output.
