### ISSUE TITLE
Operation Error: LiftOverError

### ISSUE THREAD

**Issue by qhelleu** [informationsea/transanno#3]
Hi,
I tried transanno liftvcf, but I got the following error:
thread 'main' panicked at 'Operation Error: LiftOverError { inner: Custom { kind: Other, error: "Unknown sequence name." }

unknown sequence error: NPCor_contig_874 }', transanno/src/main.rs:30:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Do you have an idea why it's not recognizing the contig names?

Thanks.

**Comment by fischuu** [comment]
Actually, I run into the exact same problem, have you been able to solve the issue?

**Comment by informationsea** [comment]
This problem was resolved in version 0.4.0 release. Please try latest version.

**Comment by fischuu** [comment]
This is just to confirm that your updated version 0.4.0 worked for me, thanks for the fix!
